### ISSUE TITLE
I want to build a blazor app with wpf

### ISSUE THREAD

**Issue by buildwithrichard** [fineboy0407/Smart_HealthCare#1]
Please help me to build blazor app with wpf.

**Comment by whateverbest** [comment]
Use these docs :
https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/wpf
https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/tutorials/wpf.md

**Comment by buildwithrichard** [comment]
I think, I can mount WPF app based on xaml browser.
